### ISSUE TITLE
unexpected character after line continuation characte

### ISSUE THREAD

**Issue by fahdmirza** [KennyVaneetvelde/atomic_agents#2]
Hi,
 Trying to install it on Ubuntu :

(atomicagents) Ubuntu@0055-kci-prxmx10068:~/atomic_agents$ python3 examples/basic_custom_chatbot.py
Traceback (most recent call last):
  File "/home/Ubuntu/atomic_agents/examples/basic_custom_chatbot.py", line 7, in <module>
    from atomic_agents.agents.base_chat_agent import BaseChatAgent
  File "/home/Ubuntu/anaconda3/envs/atomicagents/lib/python3.11/site-packages/atomic_agents/agents/base_chat_agent.py", line 5, in <module>
    from atomic_agents.lib.components.system_prompt_generator import SystemPromptGenerator
  File "/home/Ubuntu/anaconda3/envs/atomicagents/lib/python3.11/site-packages/atomic_agents/lib/components/system_prompt_generator.py", line 32
    system_prompt += f'- {'\n-'.join(self.system_prompt_info.background)}\n\n'
                            ^
SyntaxError: unexpected character after line continuation character
(atomicagents) Ubuntu@0055-kci-prxmx10068:~/atomic_agents$

Also, please include some working quickstart on main home page including setting of API keys etc.

**Comment by KennyVaneetvelde** [comment]
W00t congratz on being the first issue opener.

Could you give it another go with the latest version of the package?

As for your quickstart request, that is in the works! Should arrive ASAP

**Comment by fahdmirza** [comment]
Thanks, I am trying to review this tool for my channel https://www.youtube.com/@fahdmirza so would be good to have a good quickstart. Will check it in later today, thank you

**Comment by KennyVaneetvelde** [comment]
@fahdmirza Can you confirm if it's fixed? Also some guides and notebooks and extra examples have been added in the meanwhile, more to come but I think this is a nice start already

**Comment by fahdmirza** [comment]
Thanks, yes it works.  I have reviewed it for my channel and will make it live in few hours.  I hope that helps and please subscribe to the channel and share it. Thanks.

**Comment by KennyVaneetvelde** [comment]
Magnificent I will keep an eye on the channel and share the video in my socials! I'll close this issue now then!
